name: Lazarus Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Lazarus
      run: |
        curl -L -o lazarus.exe https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2064%20bits/Lazarus%202.2.2/lazarus-2.2.2-fpc-3.2.2-win64.exe/download
        curl -L -o lazarus-cross.exe https://sourceforge.net/projects/lazarus/files/Lazarus%20Windows%2064%20bits/Lazarus%202.2.2/lazarus-2.2.2-fpc-3.2.2-cross-i386-win32-win64.exe/download
        Start-Process -FilePath "lazarus.exe" -ArgumentList "/VERYSILENT" -Wait
        Start-Process -FilePath "lazarus-cross.exe" -ArgumentList "/VERYSILENT" -Wait
        $env:Path += ";C:\lazarus\fpc\3.2.2\bin\x86_64-win64"
        $env:Path += ";C:\lazarus\fpc\3.2.2\bin\i386-win32"

    - name: Build Cheat Engine
      working-directory: ${{ github.workspace }}/Cheat Engine
      run: |
        & "C:\lazarus\lazbuild.exe" --build-mode=Release "cheatengine.lpi"

    - name: Find and build secondary projects
      run: |
        $files = Get-ChildItem -Path $env:GITHUB_WORKSPACE -Recurse -Filter *.lpr,*.sln
        foreach ($file in $files) {
          if ($file.Extension -eq ".sln") {
            & "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" $file.FullName
          } else {
            & "C:\lazarus\lazbuild.exe" --build-mode=Release $file.FullName
          }
        }